### PR TITLE
TAM status example

### PR DESCRIPTION
**Pull request by coelner**
I made an example. it is explicitly designed for a M5StickC. But the specific parts could easily exchanged.

### CODE REVIEW

**Comment by Aypac** [comment]
Hi coelner,
thanks for the contribution!

The problem with this PR is, that is only works on the  M5StickC.h and thus the CI fails (see above). So this would have to be fixed before I can add it to the repo.
In the past I've solved this with a code fragment like this:


```
#if defined(ESP8266)
    #include <ESP8266HTTPClient.h>;
#elif defined(ESP32)
    #include <HTTPClient.h>;
#else
      //INCOMPATIBLE!
```

I guess something similar needs to be done here, also defining alternatives for the `M5.commands` used in the code. However, I don't currently have time to do that and I do not own a M5StickC.
Also, is a TAM = Telephone answering machine?

**Comment by coelner** [comment]
Yes, TAM is telephone answering machine.

Right, CI will not work. However, this MTStickC is a development platform and include a display, battery management and buttons and is build around an esp32.
I will search for a solution, but it will make it mostly useless without the display and button.

**Comment by coelner** [comment]
Your snipped just selects the architecture, which in this case is esp32 too. 
As far as I know the problem is still open and not addressed: https://github.com/arduino/Arduino/issues/1481
I encapsulated the code in its own block. If you wish I can add a separate sketch for a bare esp module. But as I said, it makes less sense without a button and a display.

and travis-ci fails completely for the esp8266 platform.

**Comment by Aypac** [comment]
Thanks, your points are fair. I think there are also ways to turn off Travis for certain folders and/or tests within folders. Maybe this could serve as a work-around until it can be done properly.

**Comment by Aypac** [comment]
By adding an empty file called `.test.skip`, Travis will be disabled. I can also add it later myself.

**Comment by coelner** [comment]
It seems that it does not work. The complete job failes, even for the exisiting examples. Not only this new one.

**Comment by gsg2820** [comment]
@coelner 
i had the same problem. after changing the Arduino IDE Version in travis.yml File the Build succeeded
ARDUINO_IDE_VERSION="1.8.13"

**Comment by coelner** [comment]
#40 travis fails because of this.
```
/home/travis/arduino_ide/libraries/Adafruit_Test_Library/src/tr064.cpp:398:15: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, host, port, uri)

  398 |     http.begin(_ip, _port, url);

      |     ~~~~~~~~~~^~~~~~~~~~~~~~~~~

exit status 1
```

**Comment by Aypac** [comment]
Ok. I will merge this into the 'new examples' branch. Then I'll debug all the new examples together with the new library version.

**Comment by gsg2820** [comment]
Shure I will test it. I will probably only have time for it on monday.
If you can. Have a look at the examples in my development branch and the secret files. Following up on my mistake to push sensitive data I find this very convenient with the extra line in gitignore

**Pull request merged**
