### PR TITLE
Adds ability to use https with and without rootCa validation (Esp32 only)

### PR DESCRIPTION
**Pull request by RoSchmi**
This PR (for Esp32) adds the ability to use secure transmission with and without rootCa validation. The examples were adapted to show how secure transmission can be achieved. The changed library should be compatible to former versions for the Esp32.

### CODE REVIEW

**Comment by RoSchmi** [comment]
Should compile now on Esp8266 as well and works with normal http requests. Secure transport is only expected to work on Esp32

**Comment by Aypac** [comment]
Thank you for your contribution!
Before merging this, I would like to see a few more people confirming this works (or confirm it myself, which is currently difficult).

**Comment by RoSchmiSec** [comment]
Hi @Aypac, thanks for your response,
if anybody wants to try an example, here is a sample for PlatformIO using secure requests.
https://github.com/RoSchmi/Esp32_Fritzbox_TR064_Phone_Absence

**Comment by Aypac** [comment]
Being included in the new version 1.3.0 (working on it).
Thanks again for your contribution!

**Pull request closed without merging**
