### PR TITLE
 Testet against 07.24-88406 BETA

### PR DESCRIPTION
**Pull request by gsg2820**
again a pull request.
i had to remove a commit.

### CODE REVIEW

**Comment by Aypac** [comment]
Thank you so much for doing all this work and thus effectively keeping this project alive!
I merged it into an intermediate develop branch, so I can do some light editing on it.

**Comment by Aypac** [comment]
Ok, can you pull the develop branch and test it? I would like to check one last time, before I push it to the version that you can install via the Arduino IDE.

**Comment by gsg2820** [comment]
Shure I will test it. I will probably only have time for it on monday.
If you can. Have a look at the examples in my development branch and the secret files. Following up on my mistake to push sensitive data I find this very convenient with the extra line in gitignore

**Comment by Aypac** [comment]
Yeah, I like it! Just wondering how it would play with the example-function in the arduino IDE... Have you tested that yet?

**Comment by gsg2820** [comment]
if you open the sketch from the example menu in the arduino IDE, the Tab "arduino_secrets_example" is present. Then you tab on the DownArrow on the right and Rename it to "arduino_secrets". Fill out your sensitive data and you are good to go.

**Comment by saak2820** [comment]
ups. I just saw a call to init in the No init example.
if(connection.state()<0){
    connection.init();
  }
that shouldn't be there.
I'm sorry

**Pull request merged**
